package appAccess;


public class AppAccess {
	
	int guessNum1 = 0;
	int guessNum2 = 0;
	int guessNum3 = 0;
	
	boolean winCondition1 = false;
	boolean winCondition2 = false;
	boolean winCondition3 = false;
	
	randomGenerator.RandomNumberGenerator playerone = new randomGenerator.RandomNumberGenerator();
	randomGenerator.RandomNumberGenerator playertwo = new randomGenerator.RandomNumberGenerator();
	randomGenerator.RandomNumberGenerator playerthree = new randomGenerator.RandomNumberGenerator();
	
	public void appAccess() {
		
		AppAccess aa = new AppAccess();
		while(true) {
			int systemAutoGeneratedNumber = (int)(Math.random()*10);
			aa.guessNum1 = playerone.randomNumberGenerator();
			aa.guessNum2 = playerone.randomNumberGenerator();
			aa.guessNum3 = playerone.randomNumberGenerator();
			
			
			if(aa.guessNum1 == systemAutoGeneratedNumber) {
				aa.winCondition1 = true;
			}
			
			if(aa.guessNum2 == systemAutoGeneratedNumber) {
				aa.winCondition2 = true;
			}
			
			if(aa.guessNum3 == systemAutoGeneratedNumber) {
				aa.winCondition3 = true;
			}
			
			if(aa.winCondition1 || aa.winCondition2 || aa.winCondition3) {
				if(aa.winCondition1) {
					System.out.println("PlayerOne won the Game. Random Guess Number By Machine: "+systemAutoGeneratedNumber+" PlayerOne Guess Number: "+aa.guessNum1);
					break;
				}
				else if(aa.winCondition2) {
					System.out.println("Playertwo won the Game. Random Guess Number By Machine:"+systemAutoGeneratedNumber+" PlayerOne Guess Number: "+aa.guessNum2);
					break;
				}
				else if(aa.winCondition3) {
					System.out.println("Playerthree won the Game. Random Guess Number By Machine: "+systemAutoGeneratedNumber+" PlayerOne Guess Number: "+aa.guessNum3);
					break;
				}
			}
		}
		System.out.println("Ending the game, App Closing...");
	}
}
